spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tRbaeFt4UNGBSzAUtfk
      secret-key: jcoKe3xZKOj4gH0FVDG5YY4mCTUnBb
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: gulimall-zhengyu

  application:
    name: gulimall-third-party

server:
  port: 30000
